// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_oMfDqwzlsi1n5UUQODVHP-6civN71ik',
    appId: '1:43720258053:web:7618dd032e2789cdafe26c',
    messagingSenderId: '43720258053',
    projectId: 'amuse-to',
    authDomain: 'amuse-to.firebaseapp.com',
    storageBucket: 'amuse-to.firebasestorage.app',
    measurementId: 'G-2R7XHV3133',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAceBE_4358iEmWhA2Xqj1JkYWRaPRVZaQ',
    appId: '1:43720258053:android:8bcb13bc4b377ddbafe26c',
    messagingSenderId: '43720258053',
    projectId: 'amuse-to',
    storageBucket: 'amuse-to.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBz6h4dkpZoGrQ_d43GKKFfeNrtQ6HGFI',
    appId: '1:43720258053:ios:3f6485b3b9811327afe26c',
    messagingSenderId: '43720258053',
    projectId: 'amuse-to',
    storageBucket: 'amuse-to.firebasestorage.app',
    iosBundleId: 'com.ryo.amuseBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBz6h4dkpZoGrQ_d43GKKFfeNrtQ6HGFI',
    appId: '1:43720258053:ios:83e8d9f2a3baf8a7afe26c',
    messagingSenderId: '43720258053',
    projectId: 'amuse-to',
    storageBucket: 'amuse-to.firebasestorage.app',
    iosBundleId: 'com.example.amuseBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_oMfDqwzlsi1n5UUQODVHP-6civN71ik',
    appId: '1:43720258053:web:e887a0dc66e2d804afe26c',
    messagingSenderId: '43720258053',
    projectId: 'amuse-to',
    authDomain: 'amuse-to.firebaseapp.com',
    storageBucket: 'amuse-to.firebasestorage.app',
    measurementId: 'G-SZXLFNN4BT',
  );
}
